<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UsesAvalonia>true</UsesAvalonia>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Hookmes.Base\Hookmes.Base.csproj" />
    <ProjectReference Include="..\Hookmes.Platform\Hookmes.Platform.csproj" />
    <ProjectReference Include="..\Hookmes.Automation\Hookmes.Automation.csproj" />
  </ItemGroup>
</Project>
