<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UsesAvalonia>true</UsesAvalonia>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hookmes.Base\Hookmes.Base.csproj" />
  </ItemGroup>

</Project>
