<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UsesAvalonia>true</UsesAvalonia>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Hackermes.Base\Hackermes.Base.csproj" />
    <ProjectReference Include="..\Hackermes.Platform\Hackermes.Platform.csproj" />
    <ProjectReference Include="..\Hackermes.Automation\Hackermes.Automation.csproj" />
  </ItemGroup>
</Project>
