// 构建 Page Agent 并生成 C# 源文件。
//
// 产物 Generated/PageAgentScript.g.cs 会提交进仓库,
// 这样常规 dotnet build 不需要 Node —— 只有改动 TS 源码时才需要跑这个脚本。

import { build } from 'esbuild';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const outDir = join(root, 'Generated');

/** 打包成单个 IIFE,不留任何模块系统痕迹。 */
async function bundle(entry) {
  const result = await build({
    entryPoints: [join(root, entry)],
    bundle: true,
    format: 'iife',
    target: 'es2020',
    platform: 'browser',
    minify: false, // 保持可读:出问题时要能在 DevTools 里看懂注入了什么
    write: false,
    legalComments: 'none',
  });

  return result.outputFiles[0].text;
}

/** 转成 C# raw string literal。用足够多的引号作分隔符,避免与脚本内容冲突。 */
function toRawStringLiteral(text) {
  let fence = '"""';
  while (text.includes(fence)) {
    fence += '"';
  }

  return `${fence}\n${text}\n${fence}`;
}

const mainScript = await bundle('src/main/entry-main.ts');
const isolatedScript = await bundle('src/isolated/entry-isolated.ts');

const csharp = `// <auto-generated />
// 由 src/Hackermes.PageAgent/build.mjs 生成,请勿手工编辑。
// 修改 TypeScript 源码后运行:npm install && npm run build

namespace Hackermes.PageAgent;

/// <summary>
/// Page Agent 脚本常量。
/// <para>
/// 注入前需把 <c>__HACKERMES_BINDING__</c> 占位符替换成本次会话的实际绑定名,
/// 见 <c>PageAgentScript.PrepareMainWorld</c>。
/// </para>
/// </summary>
public static class PageAgentScript
{
    /// <summary>脚本里等待替换的绑定名占位符。</summary>
    public const string BindingPlaceholder = "__HACKERMES_BINDING__";

    /// <summary>主世界脚本:网络 / 存储 / 路由 hook。</summary>
    public const string MainWorld = ${toRawStringLiteral(mainScript)};

    /// <summary>命名隔离世界脚本:DOM 录制与元素选择器生成。</summary>
    public const string IsolatedWorld = ${toRawStringLiteral(isolatedScript)};

    /// <summary>把占位符换成实际绑定名。</summary>
    public static string PrepareMainWorld(string bindingName) =>
        MainWorld.Replace(BindingPlaceholder, "\\"" + bindingName + "\\"");

    /// <summary>为隔离世界脚本注入仅在该世界可见的绑定名。</summary>
    public static string PrepareIsolatedWorld(string bindingName) =>
        IsolatedWorld.Replace(BindingPlaceholder, "\\"" + bindingName + "\\"");
}
`;

await mkdir(outDir, { recursive: true });
await writeFile(join(outDir, 'PageAgentScript.g.cs'), csharp, 'utf8');

console.log(`已生成 Generated/PageAgentScript.g.cs (主世界 ${mainScript.length} 字符, 隔离世界 ${isolatedScript.length} 字符)`);
