<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UsesAvalonia>true</UsesAvalonia>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Irihi.Ursa" />
    <PackageReference Include="Semi.Avalonia" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hookmes.Base\Hookmes.Base.csproj" />
    <ProjectReference Include="..\Hookmes.Platform\Hookmes.Platform.csproj" />
  </ItemGroup>

</Project>
